name: TAGZ1
favicon: null
layout_spectrum: 0.588682
typography_spectrum: 0.61424
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c0c0c0'
    - '#636363'
    - '#2f2f2f'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
