name: TAGZ1
favicon: null
layout_spectrum: 0.5058
typography_spectrum: 0.36412
title: THE HOME OF TAGZ1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c0c0c0'
    - '#636363'
    - '#2f2f2f'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
