typography_spectrum: 0.24439314752817154
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c0c0c0'
    - '#636363'
    - '#2f2f2f'
  brandStrength: 0
  lightness: 0.625
  rhythmicContrast: 0.5
  saturation: 0.75
opengraph: {}
layout_spectrum: 0.370866616955027
analytics: {}
name: TAGZ1
cta: {}
title: THE ARTWORK OF TAGZ1
coverPrefs:
  filter: false
description: things will remain the same until you change them
purpose: []
