layout_spectrum: 0.370866616955027
typography_spectrum: 0.24439314752817154
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c0c0c0'
    - '#636363'
    - '#2f2f2f'
  brandStrength: 0
  lightness: 0.625
  rhythmicContrast: 0.5
  saturation: 0.75
coverPrefs:
  filter: false
analytics: {}
cta: {}
name: THE ART OF TAGZ1
opengraph: {}
purpose: []
