layout_spectrum: 0.7274852548725903
typography_spectrum: 0.6433418267406523
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c0c0c0'
    - '#636363'
    - '#2f2f2f'
  brandStrength: 0
  lightness: 0.625
  rhythmicContrast: 0.5
  saturation: 0.75
coverPrefs:
  filter: false
opengraph: {}
analytics: {}
name: TAGZ1
cta: {}
title: THE ARTWORK OF TAGZ1
description: things will remain the same until you change them
purpose: []
