layout_spectrum: 0.7274852548725903
typography_spectrum: 0.6441411993000656
color:
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#C1C1C1'
    - '#303030'
    - '#606060'
  brandStrength: 0.9787220056168735
  lightness: 0.39043097966350615
  rhythmicContrast: 0.9348130885045975
  saturation: 0.661510476609692
coverPrefs:
  filter: false
opengraph: {}
analytics: {}
author:
  name: Robert TAGZ1 Perez
  email: robert@tagz1.com
  url: TAGZ1.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/901b6495-62c6-47c3-9bf0-18b830d65f92.png
name: TAGZ1
cta: {}
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7fb5b7c6-f2d3-4070-b3bf-0caa5d5c82a9.png
title: THE ARTWORK OF TAGZ1
description: robert@tagz1.com
purpose: []
