analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c0c0c0'
    - '#636363'
    - '#2f2f2f'
  brandStrength: 0
  lightness: 0.625
  rhythmicContrast: 0.5
  saturation: 0.75
cta: {}
layout_spectrum: 0.588682
name: TAGZ1
opengraph: {}
purpose: []
typography_spectrum: 0.564189
