typography_spectrum: 0.6433418267406523
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#c0c0c0'
    - '#636363'
    - '#2f2f2f'
  brandStrength: 0
  lightness: 0.625
  rhythmicContrast: 0.5
  saturation: 0.75
opengraph: {}
layout_spectrum: 0.7274852548725903
analytics: {}
name: TAGZ1
cta: {}
navigation:
  - name: FACEBOOK
    url: 'https://www.facebook.com/KingTAGZ1/'
    type: external
  - name: INSTAGRAM
    url: 'https://www.instagram.com/TAGZ1/'
    type: external
  - name: TWITTER
    url: 'https://twitter.com/TAGZ_ONE'
    type: external
  - name: YOUTUBE
    url: 'https://www.youtube.com/TAGZ1TV'
    type: external
title: THE ARTWORK OF TAGZ1
coverPrefs:
  filter: false
description: things will remain the same until YOU change them
purpose: []
